#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define N_BOARD_WIDTH 40
#define N_BOARD_HEIGHT 20

#define N_PLAY_AREA_WIDTH ( N_BOARD_WIDTH - 2 )
#define N_PLAY_AREA_HEIGHT ( N_BOARD_HEIGHT - 2 )
#define N_PLAY_AREA_SIZE N_PLAY_AREA_WIDTH * N_PLAY_AREA_HEIGHT 

#define S_BOARD_OFFSET_X "\t\t\t\t"

#define N_SLOW_DOWN 150

#define ESC 27
#define ENTER 13

#endif
